### ISSUE TITLE
Bad documentation?

### ISSUE THREAD

**Issue by busslina** [gskinnerTeam/flutter-context-menu#15]
Readme documentation says:

```
To get started, wrap a ContextMenuOverlay around your top-most view or app:

return ContextMenuOverlay(
  child: MaterialApp(...)
);

```

But this is giving some no directional widget found error. In the `ContextMenuOverlay` class documentation the docs are right, pointing that it should be placed somewhere in between `MaterialApp` and the top-most view.

**Comment by esDotDev** [comment]
This is fixed in the v1.1.0, you can now place the Overlay above MaterialApp.
