### ISSUE TITLE
The getter 'bodyText1' isn't defined for the class 'TextTheme'

### ISSUE THREAD

**Issue by pluzmedia** [gskinnerTeam/flutter-context-menu#17]
Hi,

Context Menu is failing to upgrade to latest version.

**Comment by Juliotati** [comment]
> Hi,
> 
> Context Menu is failing to upgrade to latest version.

Just opened a PR for that, just got to wait for the maintainer to see and merge.  
- https://github.com/gskinnerTeam/flutter-context-menu/pull/18

_(take into account this haven't been updated for at least 2 years)_

**Comment by rodrigo-itao** [comment]
Hi @esDotDev , could you please update the [pub.dev package](https://pub.dev/packages/context_menus) when you get a chance? Thanks a lot!
