### ISSUE TITLE
Add screenshots to `README.md`

### ISSUE THREAD

**Issue by nilsreichardt** [gskinnerTeam/flutter-context-menu#2]
## Description
It would be very helpful to see some screenshots, to see what the widgets look like.

**Comment by jlnrrg** [comment]
For everyone else wondering, this it how the context menu looks at default:

![image](https://user-images.githubusercontent.com/77293597/142766513-649953a9-c518-48c3-ab79-c008da1b0332.png)

**Comment by GroovinChip** [comment]
A gif demo was added to the package readme, looks like this can be closed now.
